### ISSUE TITLE
WikiHole, the short story

### ISSUE THREAD

**Issue by bdnbdy** [algorithmiaio/shorties#2]
So I get stuck in "wikiholes" pretty frequently, you know, where you just want to look up one thing real quick but somehow you keep clicking on links and then all the sudden it's hours later and you have no idea how you got to the article you're on or even what you were first reading about.

My short story is based on this experience! I made it in Ruby. [Here is the code & full text](https://gist.github.com/bdnbdy/6d456b67192e8dceb5e7).

My story starts with: 

> You know what I should look up?
> 
> > [Jock Jams ](https://en.wikipedia.org/wiki/Jock_Jams)
> 
> _Jock Jams is a series of compilation albums released by Tommy Boy Records._

Then by randomly selecting links from that page, ends up traveling to the Wikipedia article on ISBN numbers:

> This looks good: [International Standard Book Number ](https://en.wikipedia.org/wiki/International_Standard_Book_Number)
> 
> > _The International Standard Book Number (ISBN) is a unique[a][b] numeric commercial book identifier._
> 
> Hmm, intriguing.

And finally ends on the article for square dancing:

> Never heard of [Traditional square dance ](https://en.wikipedia.org/wiki/Traditional_square_dance)
> 
> > _Traditional square dance is a generic American term for any style of American square dance other than modern Western._

This short story code is fun because it is different every time you run it. When you run the script, it prompts you for a url to a wikipedia article, so you can choose the starting point for your story story.

**Comment by bdnbdy** [comment]
Oh yeah! And the algorithms I used were:
[Sentence Split](https://algorithmia.com/algorithms/StanfordNLP/SentenceSplit)
[Analyze URL](https://algorithmia.com/algorithms/web/AnalyzeURL)
[URL Link List](https://algorithmia.com/algorithms/brejnko/UrlLinkList)

**Comment by lizrush** [comment]
This is fantastic! I'm victim to the "wikihole" pretty frequently myself!

Love the use of non-NLP algorithms (& ruby!) to make a shortie--super creative!
