### ISSUE TITLE
n+7

### ISSUE THREAD

**Issue by fabianekc** [algorithmiaio/shorties#3]
Many years ago (I think it was in 2001) I participated in a class about Mathematics & Literature. Beside others the "n+7 method" was presented: You replace in a text each noun with the noun in a dictionary which is 7 places after the original noun, e.g., "a man meets a woman" is transformed to "a mandrake meets a wonder" using the Langenscheidt dictionary.

OK, here my submission:
- [Flatland_7.txt](https://github.com/fabianekc/n7/blob/master/Flatland_7.txt): the first 4 sections of Flatland by E. Abbott translated by n+7
- link to n7 on Algorithmia: https://algorithmia.com/algorithms/fabianekc/n7

Note: This is my first algorithm on Algorithmia and my first python script - bear with me! :-)  
Thanks for the contest, it was a nice exercise.

**Comment by lizrush** [comment]
Fantastic @fabianekc!! Thanks for your entry! Bonus points for adding an algorithm to the platform :grinning:
