### ISSUE TITLE
Big Dummy's Leaves of Spam

### ISSUE THREAD

**Issue by ghost** [algorithmiaio/shorties#6]
Here's my submission!:

https://leaves-of-spam.herokuapp.com/
(Details are at https://github.com/skwak/big-dummys-leaves-of-spam)

**Comment by lizrush** [comment]
OMG

>  O pensive. Loveflesh swelling and deliciously aching. Attract all matter! This solid world For my enemy is dead. Type ~r file. Programs or other files that let you use a system at MIT. Adieu dear comrade! 

This is fantastic. Love the recognizable Walt Whitman. Great mashup!!
