### ISSUE TITLE
Author Mashup!

### ISSUE THREAD

**Issue by bryantwong** [algorithmiaio/shorties#8]
This is the most last minute submission! Done with https://github.com/LoganWalls.

Lots more details are [here](https://github.com/bryantwong/shorties).

They're all equally awful so we'll just submit [Ulysses by Jane Austen](https://github.com/bryantwong/shorties/edit/master/stories/ulysses_pride_prejudice.txt) as our one story.

Thanks for the opportunity! I'm still awful at Python but it was a lot of fun

**Comment by lizrush** [comment]
Wow, this is great!! I love the concept--converting stories into parts of speech and then doing to vocab conversion from another author is really interesting!
